### ISSUE TITLE
Npm license profile is NONE

### ISSUE THREAD

**Issue by ZRktty** [cosmosio/nested-property#10]
Hello,
want to publish the package to company artifactory but license check fails even the 'licenses' key are set in package.json. Noticed, package's  npm profile show NONE for license.I guess that npm doesn't recognize the 'licenses' key in the package.json.
Changing the key to:  "license": "MIT" would possibly solve this.

**Comment by podefr** [comment]
good catch, it seems that the style I was using is now deprecated as per https://npm.github.io/using-pkgs-docs/package-json/the-package-json-file.html. I just pulished 1.0.4 with the fix, let me know if it addresses your issue, thanks!

**Comment by podefr** [comment]
I'm closing this as this issue should now be resolved, please reopen if I'm mistaken. Thanks!
