### ISSUE TITLE
CHANGELOG or Release notes?

### ISSUE THREAD

**Issue by perry-mitchell** [cosmosio/nested-property#13]
Hi, wondering if you'd consider adding a changelog or release notes, so one could track changes in an easier manner. This would make it easier to upgrade versions of nested-property as you could most likely list breaking changes in the notes as well.

What do you think?

**Comment by podefr** [comment]
Thanks for the suggestion! The changelog is at the end of the README here: https://github.com/cosmosio/nested-property

Were you suggesting a CHANGELOG as a separate file?

**Comment by perry-mitchell** [comment]
@podefr I was, but I didn't notice the changelog in the readme, sorry. I would personally suggest using a separate file as it's easier to find. 

I'll close this issue as I believe it's been answered. Thanks!

**Comment by podefr** [comment]
You're not the first one asking so I guess a separate file would be easier to locate ;) I'll make the change, thanks!
