### ISSUE TITLE
Possible introduction for array wildcards?

### ISSUE THREAD

**Issue by YussufElarif** [cosmosio/nested-property#8]
If I have an array:
```
{
   emails: [
      {
         path1: "a",
         delPath: "a@email.com"
       },
      {
         path1: "b",
         delPath: "b@email.com"
      },
      ...
   ]
}
```

I think it would be useful to be able to use wildcards like the following:
```
nestedProperty.set(obj, 'emails.*.delPath', undefined)
```
OR
```
nestedProperty.set(obj, 'emails.$.delPath', undefined)
```

Which would essentially grab all items in the array and end up like this
```
{
   emails: [
      {
         path1: "a",
         delPath: undefined
       },
      {
         path1: "b",
         delPath: undefined
      },
      ...
   ]
}
```

**Comment by YussufElarif** [comment]
I have a solution:

https://stackblitz.com/edit/nested-array-properties?file=index.ts

What do you think?

**Comment by podefr** [comment]
Thanks Yussuf I appreciate the suggestion. I agree with you that having a feature such as wildcards would be great addition to the library. A few questions for you:

1. Should the other methods (get, has, isIn) also support the wildcard pattern?
2. If we add a wildcard for a single "segment" in the path, should we also have a wildcard for an undetermined number of segments, such as: `emails.**.delPath` which could resolve something like `emails.path1.path2.path3.deaPath`
3. Could you give me more details about your use cases so I can see what kind of edge cases we may need to code for?

Last question, I like where your implementation is going, would you mind putting a PR together with code and unit tests? 

Thanks!

**Comment by YussufElarif** [comment]
To answer your questions:

---

1) I don't think the `get` method should have the wild card rule unless the purpose of it is to concatinate the results. e.g:

```
restaurants = [
   {
      menu: [
         {
            name: "1",
            quantity: 55
         },
         {
            name: "2",
            quantity: 10
         }
   },
   {
      menu: [
         {
            name: "3",
            quantity: 0
         },
         {
            name: "4",
            quantity: 18
         }
   }
]
```
by doing `get(restaurants, '*.menu.*.name')`;

It'd receive `["1", "2", "3", "4"]`

and doing `get(restaurants, '0.menu.*.name')`;

would receive `["1", "2"]`

---

2) So you're suggesting the alternate use case for this is to skip multiple objects to retrieve the field needed? Even if it could be at `emails.path1.delPath` or `emails.path1.path2.path3.delPath`, doing `emails.**.delPath` would resolve both these use cases?

---

3) The purpose which I needed the wild card is so that i can remove certain fields from my backend e.g. an email field from being exposed to the front end, for security purposes. It isn't possible for me to know how many items there are in the array so doing `users.1.email` wont resolve it specificaly

**Comment by podefr** [comment]
Thanks for the detailed reply!

1. Yes, I think that the behavior I would expect from `get` is as you describe. For consistency I think that if `set` has such behavior, `get` should have it as well, what do you think? 

2.  That's what I was suggesting but it seems too disconnected from your initial requirement (use case describe in 3.) so let's ignore the suggestion :)

3. Thanks for the clarification.

Another question. What would you expect in this case:

```
colors = [
    { r: 110, g: 120, b: 130 },
    { r: 110, g: 120, b: 130 }
];

set(colors, '0.*', 0);
```

Should it:

1. set all properties of `colors[0]` to `0`: 
2. throw an error saying that `0.*` doesn't resolve to an array?

**Comment by YussufElarif** [comment]
1) I agree, sounds good to me
2) Alright, but to expand on your suggestion, I personally don't know the demand for such feature but if it's something people want from the library, double asterisks could be used as an identifier to skip paths👌🏼

---

I think it should throw an error, if they want to override those values, they could do `set(colors, "0", { r: 0, g: 0, b: 0 })`?

**Comment by podefr** [comment]
agreed on all points. I also think that throwing an error is a better idea. I'll work on a PR over the next few days to add the wildcard to get/set.

Last 2 questions:
1. What's your preferred wildcard character? The wildcard should remind users that it's only to access all items in an array and not any key in an object so I would vote against `*`, but I'm ok with `$`. I kind of like `+` as well, what do you think?

2. Do you have more examples of usages for the `set` function that I could use to unit test the updated method? If you could think of any edge case as well that'd be great!

**Comment by YussufElarif** [comment]
Im happy with either, as long as its documented that it's a wildcard, it would be good. I'll put some examples in my stackblitz link

**Comment by podefr** [comment]
Hi Yussuf, just to let you know, I am still working on adding this feature, but I believe it's a good opportunity for removing some code duplication so it will take some time. I suspect a couple of weeks, I hope it's ok with you. thanks for your patience!

**Comment by podefr** [comment]
Hi Yussuf, I pushed a new branch (`add-array-wildcard`) with the feature. There are still a number of things I'd like to finalize on the code + documentation before releasing it to npm but if you have some time I'd love some early feedback. Don't hesitate to just copy/paste the code here into your project until the new version is released: https://github.com/cosmosio/nested-property/blob/add-array-wildcard/index.js (just keep the copyright ;))

**Comment by podefr** [comment]
oops, GitHub was a bit too clever here and proactively closed this issue due to my commit message.
I just released `nested-property@2.0.0-beta1` if you'd like to test. I've updated the tests/doc to reflect the wildcard feature. Let me know if it works for you and I'll remove the `-beta1` version. Thanks again for the suggestion!

**Comment by YussufElarif** [comment]
Thanks man, I'll test it when i get home. You've been very responsive and helpful. Much appreciated 🙏🏼

**Comment by podefr** [comment]
my pleasure, thanks for using this library! Let me know your experience with the new version and don't hesitate to file a new issue if anything comes up, I'll close this ticket for now, thanks!

**Comment by YussufElarif** [comment]
It works perfectly against my use cases. Ill implement it on my server, thanks alot :)
